const TRANSLATIONS = {
  en: {
    'menu':'Menu','collections':'Collections','peaks':'Peaks Collection',
    'explorer':'Explorer Collection','wildlife':'Wildlife Collection',
    'basecamp':'Base Camp','sea':'Sea Collection','explore':'Explore',
    'shop-all':'Shop All','new-arrivals':'New Arrivals','about':'About','help':'Help','language':'Language',
    'cart':'Cart','filter':'Filter',
    'shop-title':'Shop All','shop-sub':'Browse every collection.',
    'card-peaks':'Peaks','card-explorer':'Explorer','card-wildlife':'Wildlife',
    'card-basecamp':'Base Camp','card-sea':'Sea','card-na':'New Arrivals',
    'na-title':'New Arrivals','na-sub':'The latest from CAMP.','na-soon':'New arrivals coming soon.',
    'help-title':'Help',
    'faq-q1':'How do I place an order?',
    'faq-a1':'Browse any collection, select your item, choose your size, and add it to your cart. Proceed to checkout when you\'re ready.',
    'faq-q2':'What is your return policy?',
    'faq-a2':'We accept returns within 30 days of purchase on unworn, unwashed items with original tags attached.',
    'faq-q3':'How long does shipping take?',
    'faq-a3':'Standard shipping takes 5–7 business days. Expedited options are available at checkout.',
    'faq-q4':'Do you ship internationally?',
    'faq-a4':'Yes — we ship to most countries. Duties and taxes may apply depending on your location.',
    'help-contact':'Still need help? Contact us →',
    'form-name-label':'Name','form-first':'First Name','form-last':'Last Name',
    'form-email':'Email','form-subject':'Subject','form-message':'Message',
    'form-required':'(required)','form-submit':'Submit',
    'map-section':'Map','map':'Map',
    'signin-welcome':'Welcome back.','signin-sub':'Sign in to your CAMP account.',
    'signin-email':'Email','signin-password':'Password',
    'signin-forgot':'Forgot password?','signin-btn':'Sign In','signin-or':'or',
    'signin-create':'Create an Account',
    'signin-terms':'By signing in you agree to our',
    'signin-tos':'Terms of Service','signin-privacy':'Privacy Policy',
    'back':'Back',
  },
  es: {
    'menu':'Menú','collections':'Colecciones','peaks':'Colección Cumbres',
    'explorer':'Colección Explorador','wildlife':'Colección Fauna',
    'basecamp':'Campamento Base','sea':'Colección Mar','explore':'Explorar',
    'shop-all':'Ver Todo','new-arrivals':'Novedades','about':'Acerca de','help':'Ayuda','language':'Idioma',
    'cart':'Carrito','filter':'Filtrar',
    'shop-title':'Ver Todo','shop-sub':'Explora todas las colecciones.',
    'card-peaks':'Cumbres','card-explorer':'Explorador','card-wildlife':'Fauna',
    'card-basecamp':'Campamento Base','card-sea':'Mar','card-na':'Novedades',
    'na-title':'Novedades','na-sub':'Lo último de CAMP.','na-soon':'Novedades próximamente.',
    'help-title':'Ayuda',
    'faq-q1':'¿Cómo hago un pedido?',
    'faq-a1':'Navega por cualquier colección, selecciona tu artículo, elige tu talla y agrégalo al carrito.',
    'faq-q2':'¿Cuál es tu política de devoluciones?',
    'faq-a2':'Aceptamos devoluciones dentro de los 30 días de la compra en artículos sin usar con etiquetas originales.',
    'faq-q3':'¿Cuánto tarda el envío?',
    'faq-a3':'El envío estándar tarda 5–7 días hábiles. Hay opciones exprés disponibles en el pago.',
    'faq-q4':'¿Envían internacionalmente?',
    'faq-a4':'Sí — enviamos a la mayoría de los países. Pueden aplicarse aranceles según tu ubicación.',
    'help-contact':'¿Necesitas más ayuda? Contáctanos →',
    'form-name-label':'Nombre','form-first':'Nombre','form-last':'Apellido',
    'form-email':'Correo electrónico','form-subject':'Asunto','form-message':'Mensaje',
    'form-required':'(requerido)','form-submit':'Enviar',
    'map-section':'Mapa','map':'Mapa',
    'signin-welcome':'Bienvenido.','signin-sub':'Inicia sesión en tu cuenta CAMP.',
    'signin-email':'Correo electrónico','signin-password':'Contraseña',
    'signin-forgot':'¿Olvidaste tu contraseña?','signin-btn':'Iniciar sesión','signin-or':'o',
    'signin-create':'Crear una cuenta',
    'signin-terms':'Al iniciar sesión aceptas nuestros',
    'signin-tos':'Términos de servicio','signin-privacy':'Política de privacidad',
    'back':'Volver',
  },
  fr: {
    'menu':'Menu','collections':'Collections','peaks':'Collection Sommets',
    'explorer':'Collection Explorateur','wildlife':'Collection Faune',
    'basecamp':'Camp de Base','sea':'Collection Mer','explore':'Explorer',
    'shop-all':'Tout Voir','new-arrivals':'Nouveautés','about':'À propos','help':'Aide','language':'Langue',
    'cart':'Panier','filter':'Filtrer',
    'shop-title':'Tout Voir','shop-sub':'Parcourez toutes les collections.',
    'card-peaks':'Sommets','card-explorer':'Explorateur','card-wildlife':'Faune',
    'card-basecamp':'Camp de Base','card-sea':'Mer','card-na':'Nouveautés',
    'na-title':'Nouveautés','na-sub':'Les dernières nouveautés de CAMP.','na-soon':'Nouveautés bientôt disponibles.',
    'help-title':'Aide',
    'faq-q1':'Comment passer une commande ?',
    'faq-a1':'Parcourez une collection, sélectionnez votre article, choisissez votre taille et ajoutez-le au panier.',
    'faq-q2':'Quelle est votre politique de retour ?',
    'faq-a2':'Nous acceptons les retours dans les 30 jours pour les articles non portés avec étiquettes d\'origine.',
    'faq-q3':'Combien de temps prend la livraison ?',
    'faq-a3':'La livraison standard prend 5–7 jours ouvrables. Des options express sont disponibles.',
    'faq-q4':'Livrez-vous à l\'international ?',
    'faq-a4':'Oui — nous livrons dans la plupart des pays. Des droits de douane peuvent s\'appliquer.',
    'help-contact':'Besoin d\'aide ? Contactez-nous →',
    'form-name-label':'Nom','form-first':'Prénom','form-last':'Nom de famille',
    'form-email':'E-mail','form-subject':'Sujet','form-message':'Message',
    'form-required':'(requis)','form-submit':'Envoyer',
    'map-section':'Carte','map':'Carte',
    'signin-welcome':'Bienvenue.','signin-sub':'Connectez-vous à votre compte CAMP.',
    'signin-email':'E-mail','signin-password':'Mot de passe',
    'signin-forgot':'Mot de passe oublié ?','signin-btn':'Se connecter','signin-or':'ou',
    'signin-create':'Créer un compte',
    'signin-terms':'En vous connectant, vous acceptez nos',
    'signin-tos':'Conditions d\'utilisation','signin-privacy':'Politique de confidentialité',
    'back':'Retour',
  },
  de: {
    'menu':'Menü','collections':'Kollektionen','peaks':'Gipfel-Kollektion',
    'explorer':'Entdecker-Kollektion','wildlife':'Wildtier-Kollektion',
    'basecamp':'Basislager','sea':'Meer-Kollektion','explore':'Erkunden',
    'shop-all':'Alle kaufen','new-arrivals':'Neuheiten','about':'Über uns','help':'Hilfe','language':'Sprache',
    'cart':'Warenkorb','filter':'Filtern',
    'shop-title':'Alle kaufen','shop-sub':'Alle Kollektionen durchsuchen.',
    'card-peaks':'Gipfel','card-explorer':'Entdecker','card-wildlife':'Wildtier',
    'card-basecamp':'Basislager','card-sea':'Meer','card-na':'Neuheiten',
    'na-title':'Neuheiten','na-sub':'Das Neueste von CAMP.','na-soon':'Neuheiten demnächst.',
    'help-title':'Hilfe',
    'faq-q1':'Wie gebe ich eine Bestellung auf?',
    'faq-a1':'Stöbern Sie in einer Kollektion, wählen Sie Ihren Artikel und legen Sie ihn in den Warenkorb.',
    'faq-q2':'Was ist Ihre Rückgaberichtlinie?',
    'faq-a2':'Wir akzeptieren Rücksendungen innerhalb von 30 Tagen für ungetragene Artikel mit Original-Etiketten.',
    'faq-q3':'Wie lange dauert der Versand?',
    'faq-a3':'Der Standardversand dauert 5–7 Werktage. Expressoptionen sind beim Bezahlen verfügbar.',
    'faq-q4':'Versenden Sie international?',
    'faq-a4':'Ja — wir versenden in die meisten Länder. Zölle können anfallen.',
    'help-contact':'Noch Fragen? Kontaktieren Sie uns →',
    'form-name-label':'Name','form-first':'Vorname','form-last':'Nachname',
    'form-email':'E-Mail','form-subject':'Betreff','form-message':'Nachricht',
    'form-required':'(erforderlich)','form-submit':'Absenden',
    'map-section':'Karte','map':'Karte',
    'signin-welcome':'Willkommen zurück.','signin-sub':'Melden Sie sich bei Ihrem CAMP-Konto an.',
    'signin-email':'E-Mail','signin-password':'Passwort',
    'signin-forgot':'Passwort vergessen?','signin-btn':'Anmelden','signin-or':'oder',
    'signin-create':'Konto erstellen',
    'signin-terms':'Mit der Anmeldung stimmen Sie unseren',
    'signin-tos':'Nutzungsbedingungen','signin-privacy':'Datenschutzrichtlinie',
    'back':'Zurück',
  },
  ja: {
    'menu':'メニュー','collections':'コレクション','peaks':'ピークスコレクション',
    'explorer':'エクスプローラーコレクション','wildlife':'ワイルドライフコレクション',
    'basecamp':'ベースキャンプ','sea':'シーコレクション','explore':'探索',
    'shop-all':'全商品','new-arrivals':'新着','about':'私たちについて','help':'ヘルプ','language':'言語',
    'cart':'カート','filter':'絞り込み',
    'shop-title':'全商品','shop-sub':'全コレクションをご覧ください。',
    'card-peaks':'ピークス','card-explorer':'エクスプローラー','card-wildlife':'ワイルドライフ',
    'card-basecamp':'ベースキャンプ','card-sea':'シー','card-na':'新着',
    'na-title':'新着','na-sub':'CAMPの最新情報。','na-soon':'新着商品は近日公開予定。',
    'help-title':'ヘルプ',
    'faq-q1':'注文方法を教えてください。',
    'faq-a1':'コレクションを閲覧し、商品とサイズを選んでカートに追加してください。',
    'faq-q2':'返品ポリシーはどのようなものですか？',
    'faq-a2':'未着用・未洗濯で元のタグが付いた商品に限り、購入後30日以内の返品を受け付けます。',
    'faq-q3':'配送にはどのくらいかかりますか？',
    'faq-a3':'標準配送は5〜7営業日かかります。速達オプションもご利用いただけます。',
    'faq-q4':'海外配送はできますか？',
    'faq-a4':'はい、ほとんどの国に配送しています。関税がかかる場合があります。',
    'help-contact':'さらにサポートが必要ですか？お問い合わせ →',
    'form-name-label':'名前','form-first':'名','form-last':'姓',
    'form-email':'メールアドレス','form-subject':'件名','form-message':'メッセージ',
    'form-required':'（必須）','form-submit':'送信',
    'map-section':'マップ','map':'マップ',
    'signin-welcome':'おかえりなさい。','signin-sub':'CAMPアカウントにサインイン。',
    'signin-email':'メールアドレス','signin-password':'パスワード',
    'signin-forgot':'パスワードをお忘れですか？','signin-btn':'サインイン','signin-or':'または',
    'signin-create':'アカウント作成',
    'signin-terms':'サインインすることで、当社の',
    'signin-tos':'利用規約','signin-privacy':'プライバシーポリシー',
    'back':'戻る',
  },
  zh: {
    'menu':'菜单','collections':'系列','peaks':'山峰系列',
    'explorer':'探险家系列','wildlife':'野生动物系列',
    'basecamp':'大本营','sea':'海洋系列','explore':'探索',
    'shop-all':'全部商品','new-arrivals':'新品','about':'关于我们','help':'帮助','language':'语言',
    'cart':'购物车','filter':'筛选',
    'shop-title':'全部商品','shop-sub':'浏览所有系列。',
    'card-peaks':'山峰','card-explorer':'探险家','card-wildlife':'野生动物',
    'card-basecamp':'大本营','card-sea':'海洋','card-na':'新品',
    'na-title':'新品','na-sub':'CAMP最新产品。','na-soon':'新品即将推出。',
    'help-title':'帮助',
    'faq-q1':'如何下订单？',
    'faq-a1':'浏览任何系列，选择商品和尺码，然后添加到购物车。准备好后进行结账。',
    'faq-q2':'退货政策是什么？',
    'faq-a2':'我们接受购买后30天内未穿戴、附有原标签的商品退货。',
    'faq-q3':'配送需要多长时间？',
    'faq-a3':'标准配送需要5-7个工作日。结账时可选择快递选项。',
    'faq-q4':'您是否提供国际配送？',
    'faq-a4':'是的，我们向大多数国家配送。可能需要支付关税。',
    'help-contact':'还需要帮助？联系我们 →',
    'form-name-label':'姓名','form-first':'名字','form-last':'姓氏',
    'form-email':'电子邮件','form-subject':'主题','form-message':'消息',
    'form-required':'（必填）','form-submit':'提交',
    'map-section':'地图','map':'地图',
    'signin-welcome':'欢迎回来。','signin-sub':'登录您的CAMP账户。',
    'signin-email':'电子邮件','signin-password':'密码',
    'signin-forgot':'忘记密码？','signin-btn':'登录','signin-or':'或',
    'signin-create':'创建账户',
    'signin-terms':'登录即表示您同意我们的',
    'signin-tos':'服务条款','signin-privacy':'隐私政策',
    'back':'返回',
  }
};

function setLanguage(code) {
  const t = TRANSLATIONS[code] || TRANSLATIONS['en'];
  document.documentElement.lang = code;
  document.querySelectorAll('[data-i18n]').forEach(el => {
    const key = el.dataset.i18n;
    if (t[key] !== undefined) el.textContent = t[key];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el => {
    const key = el.dataset.i18nPh;
    if (t[key] !== undefined) el.placeholder = t[key];
  });
  document.querySelectorAll('.menu-lang-select').forEach(s => s.value = code);
  try { localStorage.setItem('camp-lang', code); } catch(e) {}
}

document.addEventListener('DOMContentLoaded', function() {
  let saved = 'en';
  try { saved = localStorage.getItem('camp-lang') || 'en'; } catch(e) {}
  if (saved !== 'en') setLanguage(saved);
});
