var CAMP_PRODUCTS = {
  'ridge-shell-jacket':{id:'ridge-shell-jacket',name:'Ridge Shell Jacket',collection:'Peaks Collection',collectionUrl:'peaks-collection.html',price:198,emoji:'⛰️',isNew:false,description:'Built for the ridgeline. The Ridge Shell is a 3-layer waterproof-breathable jacket designed for high-output alpine pursuits. Seam-sealed construction, pit-zip ventilation, and a helmet-compatible hood that actually works in the wind.',details:['3-layer waterproof-breathable construction','Fully seam-sealed','Helmet-compatible adjustable hood','Pit-zip ventilation','Two hand pockets + internal chest pocket','Packable into chest pocket'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:6,S:9,M:14,L:7,XL:2,XXL:5},colors:['Olive','Slate','Ink'],related:['summit-fleece','ascent-pant','trail-jacket'],giftCategory:['peak-bagger','over100']},
  'summit-fleece':{id:'summit-fleece',name:'Summit Fleece',collection:'Peaks Collection',collectionUrl:'peaks-collection.html',price:124,emoji:'🏔️',isNew:false,description:'The Summit Fleece is our go-to mid-layer for cold mornings and cool evenings on the mountain. Mid-weight fleece with a clean silhouette that works as well in camp as on the trail.',details:['Mid-weight fleece fabric','Full-zip with chin guard','Zip hand pockets','Relaxed through the body','Smooth face fabric resists wind'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:0,S:8,M:13,L:6,XL:4,XXL:3},colors:['Moss','Slate','Cream'],related:['ridge-shell-jacket','ascent-pant','camp-fleece'],giftCategory:['peak-bagger','under150']},
  'ascent-pant':{id:'ascent-pant',name:'Ascent Pant',collection:'Peaks Collection',collectionUrl:'peaks-collection.html',price:165,emoji:'🏕️',isNew:false,description:'A technical softshell pant built for the approach and beyond. The Ascent Pant moves with you on steep terrain and stays comfortable on the long descents.',details:['4-way stretch softshell','DWR finish','Articulated knees','Gusseted crotch','Two zip hand pockets','Internal ankle gaiter'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:5,S:10,M:11,L:3,XL:7,XXL:2},colors:['Ink','Slate'],related:['ridge-shell-jacket','summit-fleece','camp-pant'],giftCategory:['peak-bagger','over100']},
  'peak-beanie':{id:'peak-beanie',name:'Peak Beanie',collection:'Peaks Collection',collectionUrl:'peaks-collection.html',price:38,emoji:'🧢',isNew:false,description:'Simple, warm, and built to stay on in the wind. The Peak Beanie is double-layered merino for genuine warmth without the bulk.',details:['100% merino wool','Double-layer construction','Ribbed cuff','One size fits most','Machine washable'],sizes:['One Size'],stock:{'One Size':12},colors:['Olive','Ink','Cream'],related:['summit-fleece','ridge-shell-jacket','base-camp-beanie'],giftCategory:['under50','peak-bagger','stocking-stuffer']},
  'trail-jacket':{id:'trail-jacket',name:'Trail Jacket',collection:'Explorer Collection',collectionUrl:'explorer-collection.html',price:186,emoji:'🌲',isNew:true,description:"A lightweight, packable wind jacket for the days when you're not sure what the weather will do. Stuffs into its own chest pocket and weighs almost nothing.",details:['Ripstop nylon shell','Packable into chest pocket','Adjustable hood and hem','Two hand pockets','DWR finish','Reflective details'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:4,S:7,M:10,L:8,XL:5,XXL:2},colors:['Sage','Stone','Bark'],related:['explorer-vest','field-shirt','ridge-shell-jacket'],giftCategory:['explorer','over100']},
  'explorer-vest':{id:'explorer-vest',name:'Explorer Vest',collection:'Explorer Collection',collectionUrl:'explorer-collection.html',price:98,emoji:'🗺️',isNew:false,description:"The Explorer Vest is a lightweight insulated layer you'll reach for constantly. Six pockets give you a place for everything from trail snacks to a map.",details:['PrimaLoft Gold insulation','6 pockets total','Wind-resistant face fabric','Packable','Stretch side panels','Hem adjustment'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:7,S:9,M:12,L:6,XL:3,XXL:1},colors:['Olive','Bark','Slate'],related:['trail-jacket','field-shirt','camp-fleece'],giftCategory:['explorer','under100']},
  'field-shirt':{id:'field-shirt',name:'Field Shirt',collection:'Explorer Collection',collectionUrl:'explorer-collection.html',price:88,emoji:'🌿',isNew:false,description:"A rugged cotton-nylon blend shirt for days that start at the trailhead and end somewhere unexpected. Chest pockets, roll-tab sleeves, relaxed fit.",details:['Cotton-nylon blend','Two chest pockets with button flaps','Roll-tab sleeves','Slightly relaxed fit','Button-down collar','Machine washable'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:5,S:11,M:14,L:9,XL:6,XXL:4},colors:['Khaki','Olive','Blue Fog'],related:['explorer-vest','trail-cap','trail-jacket'],giftCategory:['explorer','under100']},
  'trail-cap':{id:'trail-cap',name:'Trail Cap',collection:'Explorer Collection',collectionUrl:'explorer-collection.html',price:42,emoji:'🧢',isNew:false,description:"A structured cap with a pre-curved brim and moisture-wicking sweatband. Stays put when the wind picks up.",details:['Structured 6-panel','Moisture-wicking sweatband','Pre-curved brim','Adjustable back closure','UPF 30+'],sizes:['One Size'],stock:{'One Size':18},colors:['Olive','Bark','Ink'],related:['field-shirt','explorer-vest','nature-cap'],giftCategory:['under50','explorer','stocking-stuffer']},
  'wilderness-hoodie':{id:'wilderness-hoodie',name:'Wilderness Hoodie',collection:'Wildlife Collection',collectionUrl:'wildlife-collection.html',price:136,emoji:'🐻',isNew:true,description:"A heavyweight fleece hoodie made to be pulled on at the end of a long day. Kangaroo pocket, generous hood, relaxed fit that works over layers.",details:['Heavyweight fleece','Kangaroo hand pocket','Lined hood','Thumbhole cuffs','Relaxed fit','Pre-washed for softness'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:6,S:2,M:9,L:7,XL:4,XXL:3},colors:['Forest','Bark','Cream'],related:['forest-tee','wildlife-crew','camp-fleece'],giftCategory:['wildlife','under150']},
  'forest-tee':{id:'forest-tee',name:'Forest Tee',collection:'Wildlife Collection',collectionUrl:'wildlife-collection.html',price:58,emoji:'🌳',isNew:false,description:"A soft, slightly heavier tee in a cotton-modal blend that gets better with every wash.",details:['Cotton-modal blend','Slightly relaxed fit','Ribbed crewneck','Pre-washed','Machine washable','Side seams for shape'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:8,S:13,M:16,L:10,XL:5,XXL:3},colors:['Forest','Bark','Rust','Cream'],related:['wildlife-crew','wilderness-hoodie','shoreline-tee'],giftCategory:['wildlife','under100','stocking-stuffer']},
  'wildlife-crew':{id:'wildlife-crew',name:'Wildlife Crew',collection:'Wildlife Collection',collectionUrl:'wildlife-collection.html',price:112,emoji:'🦌',isNew:false,description:"A mid-weight crew neck sweatshirt in French terry. The Wildlife Crew is the piece you'll always want nearby when the temperature drops.",details:['French terry cotton blend','Ribbed cuffs and hem','Set-in sleeves','Relaxed fit','Side-seam pockets','Machine washable'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:4,S:7,M:11,L:8,XL:2,XXL:1},colors:['Forest','Slate','Rust'],related:['wilderness-hoodie','forest-tee','harbor-crew-fleece'],giftCategory:['wildlife','under150']},
  'nature-cap':{id:'nature-cap',name:'Nature Cap',collection:'Wildlife Collection',collectionUrl:'wildlife-collection.html',price:42,emoji:'🍂',isNew:false,description:"An unstructured 5-panel cap in washed canvas. Low-profile, adjustable, and built for the long haul.",details:['Washed canvas','Unstructured 5-panel','Fabric closure','Low-profile fit','Cotton sweatband'],sizes:['One Size'],stock:{'One Size':22},colors:['Bark','Forest','Ink'],related:['forest-tee','wildlife-crew','trail-cap'],giftCategory:['under50','wildlife','stocking-stuffer']},
  'camp-fleece':{id:'camp-fleece',name:'Camp Fleece',collection:'Base Camp',collectionUrl:'base-camp-collection.html',price:124,emoji:'⛺',isNew:false,description:"Your around-camp layer. Lightweight, warm enough on its own, and packable enough to go anywhere. A core piece in any kit.",details:['Lightweight fleece','Quarter-zip','Two zip hand pockets','Slim fit','Chin-guard zipper','Packable'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:5,S:8,M:12,L:9,XL:6,XXL:2},colors:['Olive','Cream','Slate'],related:['base-layer-top','camp-pant','summit-fleece'],giftCategory:['camp','under150']},
  'base-layer-top':{id:'base-layer-top',name:'Base Layer Top',collection:'Base Camp',collectionUrl:'base-camp-collection.html',price:76,emoji:'🏕️',isNew:false,description:"A next-to-skin merino base layer that regulates temperature in both cold and warm conditions. Wears all day without a refresh.",details:['100% merino wool','Flatlock seams','Crew neck','Slim fit','Machine washable','Naturally odor-resistant'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:6,S:9,M:13,L:7,XL:4,XXL:3},colors:['Cream','Slate','Ink'],related:['camp-fleece','camp-pant','summit-fleece'],giftCategory:['camp','under100']},
  'camp-pant':{id:'camp-pant',name:'Camp Pant',collection:'Base Camp',collectionUrl:'base-camp-collection.html',price:112,emoji:'🏕️',isNew:false,description:"A relaxed camp pant with enough structure for the trail. Elastic waist, side pockets, relaxed taper that works over base layers.",details:['Cotton-nylon blend','Elastic waistband with drawcord','Side hand pockets','Back patch pocket','Relaxed tapered fit','Machine washable'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:3,S:7,M:10,L:8,XL:4,XXL:2},colors:['Olive','Bark','Ink'],related:['base-layer-top','camp-fleece','ascent-pant'],giftCategory:['camp','under150']},
  'base-camp-beanie':{id:'base-camp-beanie',name:'Base Camp Beanie',collection:'Base Camp',collectionUrl:'base-camp-collection.html',price:38,emoji:'⛺',isNew:false,description:"A no-nonsense beanie in a medium-weight acrylic knit. Toss it in your bag and forget about it until you need it.",details:['Acrylic knit','Single-layer','Ribbed cuff folds up','One size fits most','Machine washable'],sizes:['One Size'],stock:{'One Size':28},colors:['Olive','Cream','Ink','Bark'],related:['camp-fleece','peak-beanie','nature-cap'],giftCategory:['under50','camp','stocking-stuffer']},
  'harbor-crew-fleece':{id:'harbor-crew-fleece',name:'Harbor Crew Fleece',collection:'Sea Collection',collectionUrl:'sea-collection.html',price:124,emoji:'⚓',isNew:true,description:"A salty take on the crew fleece. The Harbor Crew is made from a textured boucle fleece that holds its shape session after session.",details:['Textured boucle fleece','Crew neck','Ribbed cuffs and hem','Two hand pockets','Relaxed fit','Machine washable'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:4,S:6,M:9,L:7,XL:3,XXL:2},colors:['Marine','Fog','Cream'],related:['tide-jacket','shoreline-tee','wildlife-crew'],giftCategory:['sea','under150']},
  'tide-jacket':{id:'tide-jacket',name:'Tide Jacket',collection:'Sea Collection',collectionUrl:'sea-collection.html',price:218,emoji:'🌊',isNew:true,description:"Built for the water's edge. A waterproof shell with a maritime aesthetic — clean seams, relaxed silhouette, and details that stand up to salt and spray.",details:['Waterproof-breathable shell','Fully seam-sealed','Two-way front zip','Internal mesh lining','Adjustable hood and cuffs','Salt-resistant hardware'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:2,S:5,M:8,L:6,XL:3,XXL:1},colors:['Marine','Fog','Ink'],related:['harbor-crew-fleece','shoreline-tee','ridge-shell-jacket'],giftCategory:['sea','over100']},
  'shoreline-tee':{id:'shoreline-tee',name:'Shoreline Tee',collection:'Sea Collection',collectionUrl:'sea-collection.html',price:64,emoji:'🏄',isNew:false,description:"A lightweight linen-cotton tee that breathes well in the heat. Cut slightly longer for a relaxed, hang-loose fit.",details:['Linen-cotton blend','Relaxed fit','Slightly longer hem','Ribbed crewneck','Preshrunk','Machine washable'],sizes:['XS','S','M','L','XL','XXL'],stock:{XS:7,S:11,M:14,L:9,XL:6,XXL:3},colors:['Fog','Marine','Cream','Sand'],related:['harbor-crew-fleece','maritime-cap','forest-tee'],giftCategory:['sea','under100','stocking-stuffer']},
  'maritime-cap':{id:'maritime-cap',name:'Maritime Cap',collection:'Sea Collection',collectionUrl:'sea-collection.html',price:42,emoji:'⚓',isNew:false,description:"A 6-panel structured cap in waxed cotton. Built to handle sea spray and last a long time doing it.",details:['Waxed cotton shell','Structured 6-panel','Pre-curved brim','Adjustable brass closure','Moisture-wicking sweatband'],sizes:['One Size'],stock:{'One Size':15},colors:['Marine','Fog','Bark'],related:['tide-jacket','harbor-crew-fleece','trail-cap'],giftCategory:['under50','sea','stocking-stuffer']}
};

function getStockForSize(product, size) {
  if (!product.stock) return 99;
  return product.stock[size] !== undefined ? product.stock[size] : 99;
}

function getStockLabel(count) {
  if (count === 0) return {text: 'Sold Out', cls: 'stock-out'};
  if (count <= 3) return {text: 'Only ' + count + ' left', cls: 'stock-low'};
  return null;
}

function getTotalStock(product) {
  if (!product.stock) return 99;
  return Object.values(product.stock).reduce(function(a,b){return a+b;}, 0);
}
